import type { Artifact, Mission, ProductBrief } from "./types";

function list(items: string[]): string {
  return items.map((item) => `- ${item}`).join("\n");
}

function briefMarkdown(brief: ProductBrief): string {
  return `# ${brief.title}

## Outcome

${brief.summary}

## Primary user

${brief.primaryUser}

## Core loop

${list(brief.coreLoop)}

## Access

${brief.accessModel}

## Visual direction

${brief.visualDirection}

## Acceptance criteria

${list(brief.acceptanceCriteria)}

## Assumptions

${list(brief.assumptions)}

## Deferred

${list(brief.deferredDecisions)}
`;
}

function architectureMarkdown(brief: ProductBrief): string {
  const dataLayer = brief.requiresDatabase
    ? "Neon Postgres behind server-owned data access"
    : "No persistent data layer in V1";

  return `# Architecture — ${brief.title}

## Runtime boundary

- Next.js application with a responsive server-rendered shell
- ${dataLayer}
- Vercel preview deployment behind an explicit connector approval gate
- Browser receives no provider credentials

## Product boundary

The build optimizes this loop:

${list(brief.coreLoop)}

## Access model

${brief.accessModel}

## Failure policy

- Provider creation errors fail closed.
- Ambiguous external writes enter reconciliation-required state.
- Deployment never becomes runnable before the local build artifact exists.
- Independent verification owns acceptance evidence.
`;
}

function safeSqlName(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .toLowerCase();
}

function schemaSql(brief: ProductBrief): string {
  return brief.dataModel
    .map((entity) => {
      const table = `${safeSqlName(entity.name)}s`;
      const specificColumns = entity.fields
        .filter((field) => !["id", "created_at", "updated_at"].includes(field))
        .map((field) => `  ${safeSqlName(field)} text not null`)
        .join(",\n");
      const columns = [
        "  id uuid primary key default gen_random_uuid()",
        specificColumns,
        "  created_at timestamptz not null default now()",
      ].filter(Boolean);

      return `-- ${entity.purpose}\ncreate table if not exists ${table} (\n${columns.join(",\n")}\n);`;
    })
    .join("\n\n");
}

function sourceArtifact(brief: ProductBrief): string {
  return `"use client";

import { useState } from "react";

const seed = [
  { id: 1, title: "A clearer first-run experience", votes: 18, status: "Planned" },
  { id: 2, title: "Weekly progress digest", votes: 12, status: "Reviewing" },
];

export default function ProductPage() {
  const [items, setItems] = useState(seed);
  const [title, setTitle] = useState("");

  function submit(event: React.FormEvent) {
    event.preventDefault();
    if (!title.trim()) return;
    setItems([{ id: Date.now(), title: title.trim(), votes: 1, status: "New" }, ...items]);
    setTitle("");
  }

  return (
    <main>
      <p>PUBLIC FEEDBACK BOARD</p>
      <h1>${brief.title}</h1>
      <p>${brief.outcome}</p>
      <form onSubmit={submit}>
        <label htmlFor="idea">Share an idea</label>
        <input id="idea" value={title} onChange={(event) => setTitle(event.target.value)} />
        <button type="submit">Submit idea</button>
      </form>
      {items.map((item) => (
        <article key={item.id}>
          <strong>{item.title}</strong>
          <span>{item.status}</span>
          <button onClick={() => setItems(items.map((candidate) =>
            candidate.id === item.id ? { ...candidate, votes: candidate.votes + 1 } : candidate
          ))}>▲ {item.votes}</button>
        </article>
      ))}
    </main>
  );
}
`;
}

function readmeMarkdown(brief: ProductBrief): string {
  return `# ${brief.title}

Generated by a SharedNet Website Launch Mission.

## Run locally

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

## Product outcome

${brief.outcome}

## Infrastructure truth

Resources labeled SIMULATED are demo manifests, not provider resources. Live creation requires server-side credentials and explicit approval.
`;
}

function verificationMarkdown(mission: Mission): string {
  return `# Verification — ${mission.title}

Independent verifier: \`@sharednet/quality\`

${mission.verificationChecks
  .map(
    (check) =>
      `- [${check.status === "passed" ? "x" : " "}] ${check.label}\n  - Evidence: ${check.evidence}`,
  )
  .join("\n")}
`;
}

export function createHandoffArtifacts(mission: Mission): Artifact[] {
  const { brief } = mission;
  const artifacts: Artifact[] = [
    {
      id: "product-brief",
      name: "PRODUCT_BRIEF.md",
      kind: "brief",
      language: "markdown",
      content: briefMarkdown(brief),
      producedBy: "@sharednet/product",
      redacted: false,
    },
    {
      id: "architecture",
      name: "ARCHITECTURE.md",
      kind: "architecture",
      language: "markdown",
      content: architectureMarkdown(brief),
      producedBy: "@sharednet/architect",
      redacted: false,
    },
    ...(brief.requiresDatabase
      ? [
          {
            id: "schema",
            name: "schema.sql",
            kind: "schema" as const,
            language: "sql",
            content: schemaSql(brief),
            producedBy: "@sharednet/neon" as const,
            redacted: false,
          },
        ]
      : []),
    {
      id: "source",
      name: "app/page.tsx",
      kind: "source",
      language: "tsx",
      content: sourceArtifact(brief),
      producedBy: "@sharednet/builder",
      redacted: false,
    },
    {
      id: "readme",
      name: "README.md",
      kind: "readme",
      language: "markdown",
      content: readmeMarkdown(brief),
      producedBy: "@sharednet/builder",
      redacted: false,
    },
    {
      id: "infrastructure",
      name: "infrastructure.json",
      kind: "manifest",
      language: "json",
      content: JSON.stringify(
        {
          notice: "Secrets redacted. SIMULATED resources do not exist at providers.",
          connectors: mission.connectors,
        },
        null,
        2,
      ),
      producedBy: "@sharednet/vercel",
      redacted: true,
    },
    {
      id: "verification",
      name: "VERIFICATION.md",
      kind: "verification",
      language: "markdown",
      content: verificationMarkdown(mission),
      producedBy: "@sharednet/quality",
      redacted: false,
    },
  ];

  return artifacts;
}

export function isHandoffComplete(mission: Mission): boolean {
  const requiredNames = [
    "PRODUCT_BRIEF.md",
    "ARCHITECTURE.md",
    ...(mission.brief.requiresDatabase ? ["schema.sql"] : []),
    "app/page.tsx",
    "README.md",
    "infrastructure.json",
    "VERIFICATION.md",
  ];
  const artifactNames = new Set(mission.artifacts.map((artifact) => artifact.name));

  return (
    mission.status === "completed" &&
    mission.verificationChecks.every((check) => check.status === "passed") &&
    requiredNames.every((name) => artifactNames.has(name))
  );
}
