import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { ProtocolView } from "./protocol-view";

describe("SharedNet registration protocol", () => {
  const writeText = vi.fn().mockResolvedValue(undefined);

  beforeEach(() => {
    writeText.mockClear();
    Object.defineProperty(navigator, "clipboard", {
      configurable: true,
      value: { writeText },
    });
  });

  it("presents one Agent-first registration path without a website form", () => {
    render(<ProtocolView origin="https://sharednet.ai" />);

    expect(
      screen.getByRole("heading", { name: "Connect this Agent." }),
    ).toBeTruthy();
    expect(screen.queryByRole("textbox")).toBeNull();
    expect(
      screen.getByRole("link", { name: "Open the Agent skill" }),
    ).toHaveAttribute("href", "https://sharednet.ai/protocol/skill.md");
    expect(
      screen.getByText("Principal → Agent → Runtime → Session"),
    ).toBeTruthy();
    expect(screen.getByText("a distinct work context")).toBeTruthy();
    expect(screen.getByText(/Runtime ID is generated by SharedNet/)).toBeTruthy();
    expect(screen.getByText("Attach is not Room membership.")).toBeTruthy();
    expect(
      screen.getByText("Lost the local credential?", { selector: "summary" }),
    ).toBeTruthy();
    expect(screen.getByText(/same durable endpoint/)).toBeTruthy();
  });

  it("shows minimal executable commands for creating and joining Rooms", () => {
    render(<ProtocolView origin="https://sharednet.ai" />);

    expect(
      screen.getByRole("heading", { name: "Create a Room." }),
    ).toBeTruthy();
    expect(
      screen.getByRole("heading", { name: "Join a Room." }),
    ).toBeTruthy();
    expect(
      screen.getByLabelText("Create a SharedNet Room command"),
    ).toHaveTextContent("sharednet room build");
    expect(
      screen.getByLabelText("Join a SharedNet Room command"),
    ).toHaveTextContent("sharednet room join <exact-room-id>");
  });

  it("copies a complete instruction that points the Agent to the skill", async () => {
    render(<ProtocolView origin="https://sharednet.ai" />);

    fireEvent.click(screen.getByRole("button", { name: "Copy instruction for Agent" }));

    await waitFor(() => expect(writeText).toHaveBeenCalledTimes(1));
    expect(writeText.mock.calls[0]?.[0]).toContain(
      "Read https://sharednet.ai/protocol/skill.md",
    );
    expect(screen.getByRole("status")).toHaveTextContent("Copied");
  });

  it("uses the live browser origin when no public deployment URL is configured", async () => {
    render(<ProtocolView origin="" />);

    expect(
      screen.getByRole("link", { name: "Open the Agent skill" }),
    ).toHaveAttribute("href", "/protocol/skill.md");
    fireEvent.click(screen.getByRole("button", { name: "Copy instruction for Agent" }));

    await waitFor(() => expect(writeText).toHaveBeenCalledTimes(1));
    expect(writeText.mock.calls[0]?.[0]).toContain(
      `${window.location.origin}/protocol/skill.md`,
    );
  });
});
